So I am back on it this monday
From what I remember I was running the run.py successfully last time which was massive, but it was slow as fuck and I suspect because of multithreating with 0 workers! because it was causing an error with more than 0. So today my plan is to try with the max number and debug and see where we get to. 

1. I moved all the yamos out of experiment/cDDPM into just experiment as it was causing an error
Ok so then I pushed and made some changes to the create dataset.py functionality in order to try and resolve this issue